# Generated by Django 6.0.1 on 2026-02-18 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('key', models.SlugField(help_text='key used in frontend & backend (player_id, zone, server)')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TopUpFieldHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='topup/field_help/')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helps', to='topup.topupfield')),
            ],
        ),
        migrations.CreateModel(
            name='TopUpGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='topup/games/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topup', to='catalog.product')),
            ],
        ),
        migrations.AddField(
            model_name='topupfield',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='topup.topupgame'),
        ),
        migrations.CreateModel(
            name='TopUpPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.CharField(help_text='Example: 60 Diamonds / 325 UC', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='topup/packages/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('stock_mode', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('manual_fulfillment_time', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='topup.topupgame')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TopUpUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.JSONField(help_text='User inputs like player_id, zone, server...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to='topup.topupgame')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_data', to='orders.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='topupfield',
            index=models.Index(fields=['game'], name='topup_topup_game_id_ba7659_idx'),
        ),
        migrations.AddIndex(
            model_name='topupfield',
            index=models.Index(fields=['key'], name='topup_topup_key_bbd96d_idx'),
        ),
        migrations.AddConstraint(
            model_name='topupfield',
            constraint=models.UniqueConstraint(fields=('game', 'key'), name='unique_game_field_key'),
        ),
        migrations.AddIndex(
            model_name='topuppackage',
            index=models.Index(fields=['game'], name='topup_topup_game_id_852cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='topuppackage',
            index=models.Index(fields=['is_active'], name='topup_topup_is_acti_c1e785_idx'),
        ),
        migrations.AddIndex(
            model_name='topupuserdata',
            index=models.Index(fields=['user'], name='topup_topup_user_id_591da2_idx'),
        ),
        migrations.AddIndex(
            model_name='topupuserdata',
            index=models.Index(fields=['game'], name='topup_topup_game_id_0634a1_idx'),
        ),
    ]
