# Generated by Django 6.0.1 on 2026-02-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topuppackage',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='topuppackage',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topuppackage',
            name='stock_mode',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20),
        ),
    ]
