# Generated by Django 6.0.1 on 2026-02-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup', '0002_alter_topuppackage_options_topuppackage_is_popular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topupfield',
            name='input_length',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
