# Generated by Django 6.0.1 on 2026-02-26 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topup', '0003_topupfield_input_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topupfield',
            old_name='input_length',
            new_name='min_input_length',
        ),
    ]
