# Generated by Django 6.0.1 on 2026-03-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup', '0004_rename_input_length_topupfield_min_input_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topuppackage',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
    ]
