# Generated by Django 6.0.1 on 2026-03-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup', '0005_alter_topuppackage_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuppackage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
