# Generated by Django 6.0.1 on 2026-03-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topup', '0006_topuppackage_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topuppackage',
            name='is_featured',
        ),
    ]
