# Generated by Django 6.0.1 on 2026-03-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client_secret',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='EGP', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='gateway_code',
            field=models.CharField(help_text="Unique code to identify gateway logic (e.g., 'paymob', 'stripe')", max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('intended', 'Intended'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
