# Generated by Django 6.0.1 on 2026-03-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_client_secret_payment_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='gateway_type',
            field=models.CharField(choices=[('paymob', 'Paymob'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='paymob', help_text='The underlying provider for this gateway method', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='integration_id',
            field=models.CharField(blank=True, help_text="The provider's integration ID for this specific payment method", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_code',
            field=models.CharField(help_text="Unique code to identify this specific method (e.g., 'paymob_wallet', 'paymob_card')", max_length=50, null=True, unique=True),
        ),
    ]
