# Generated by Django 6.0.1 on 2026-03-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_order_id',
            field=models.CharField(blank=True, db_index=True, help_text='The internal order ID returned by the payment gateway', max_length=255, null=True),
        ),
    ]
