# Generated by Django 6.0.1 on 2026-03-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_exchangeratesnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('intended', 'Intended'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
