# Generated by Django 6.0.1 on 2026-03-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
