# Generated by Django 6.0.1 on 2026-03-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_adminprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
