# Generated by Django 6.0.1 on 2026-03-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='activity_type',
            field=models.CharField(choices=[('register', 'Register'), ('login', 'Login'), ('logout', 'Logout'), ('refresh_token', 'Refresh Token'), ('change_password', 'Change Password'), ('forgot_password', 'Forgot Password'), ('reset_password', 'Reset Password'), ('verify_email', 'Verify Email'), ('resend_otp', 'Resend OTP')], db_index=True, max_length=50),
        ),
    ]
