# Generated by Django 6.0.1 on 2026-03-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_useractivitylog_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='currency',
            field=models.CharField(choices=[('egp', 'EGP'), ('usd', 'USD'), ('eur', 'EUR'), ('gbp', 'GBP'), ('jpy', 'JPY')], default='egp', max_length=3),
        ),
    ]
