# Generated by Django 6.0.1 on 2026-03-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usersettings_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='currency',
            field=models.CharField(choices=[('egp', 'EGP'), ('usd', 'USD'), ('eur', 'EUR'), ('gbp', 'GBP'), ('jpy', 'JPY')], default='usd', max_length=3),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='language_preference',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ar', 'Arabic')], max_length=50, null=True),
        ),
    ]
