# Generated by Django 6.0.1 on 2026-03-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_usersettings_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='currency',
            field=models.CharField(blank=True, choices=[('egp', 'EGP'), ('usd', 'USD'), ('eur', 'EUR'), ('gbp', 'GBP'), ('jpy', 'JPY')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=50),
        ),
    ]
