# Generated by Django 6.0.1 on 2026-03-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_usersettings_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='currency',
            field=models.CharField(choices=[('egp', 'EGP'), ('usd', 'USD'), ('eur', 'EUR'), ('gbp', 'GBP'), ('jpy', 'JPY')], default='usd', max_length=4),
        ),
    ]
