# Generated by Django 6.0.1 on 2026-03-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_usersettings_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='activity_type',
            field=models.CharField(choices=[('register', 'Register'), ('login', 'Login'), ('logout', 'Logout'), ('refresh_token', 'Refresh Token'), ('change_password', 'Change Password'), ('forgot_password', 'Forgot Password'), ('reset_password', 'Reset Password'), ('verify_email', 'Verify Email'), ('resend_otp', 'Resend OTP'), ('order_create', 'Order Create'), ('order_cancel', 'Order Cancel'), ('payment_success', 'Payment Success'), ('payment_fail', 'Payment Fail')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('EGP', 'EGP'), ('CHF', 'CHF'), ('SEK', 'SEK'), ('NOK', 'NOK'), ('DKK', 'DKK'), ('PLN', 'PLN'), ('CZK', 'CZK'), ('HUF', 'HUF'), ('RON', 'RON'), ('CAD', 'CAD'), ('BRL', 'BRL'), ('MXN', 'MXN'), ('ARS', 'ARS'), ('CLP', 'CLP'), ('JPY', 'JPY'), ('KRW', 'KRW'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('TWD', 'TWD'), ('SGD', 'SGD'), ('MYR', 'MYR'), ('THB', 'THB'), ('INR', 'INR'), ('IDR', 'IDR'), ('PHP', 'PHP'), ('VND', 'VND'), ('SAR', 'SAR'), ('AED', 'AED'), ('QAR', 'QAR'), ('KWD', 'KWD'), ('BHD', 'BHD'), ('OMR', 'OMR'), ('TRY', 'TRY'), ('ZAR', 'ZAR'), ('NGN', 'NGN')], default='USD', max_length=4),
        ),
    ]
