# Generated by Django 6.0.1 on 2026-02-18 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0002_initial'),
        ('topup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('scope', models.CharField(choices=[('product', 'Product'), ('category', 'Category'), ('package', 'Package'), ('global', 'Global')], max_length=20)),
                ('discount_type', models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('percent', 'Percent')], max_length=10, null=True)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('max_usage', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='coupons_cou_code_3bf721_idx'), models.Index(fields=['is_active'], name='coupons_cou_is_acti_a50634_idx'), models.Index(fields=['scope'], name='coupons_cou_scope_f6f80b_idx'), models.Index(fields=['start_at', 'end_at'], name='coupons_cou_start_a_64e734_idx')],
            },
        ),
        migrations.CreateModel(
            name='CouponCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percent')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_categories', to='catalog.category')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_discounts', to='coupons.coupon')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('coupon', 'category'), name='unique_coupon_category')],
            },
        ),
        migrations.CreateModel(
            name='CouponPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percent')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_discounts', to='coupons.coupon')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_packages', to='topup.topuppackage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('coupon', 'package'), name='unique_coupon_package')],
            },
        ),
        migrations.CreateModel(
            name='CouponProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percent')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_discounts', to='coupons.coupon')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_products', to='catalog.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('coupon', 'product'), name='unique_coupon_product')],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['coupon'], name='coupons_cou_coupon__e70d11_idx'), models.Index(fields=['user'], name='coupons_cou_user_id_50cd03_idx'), models.Index(fields=['order'], name='coupons_cou_order_i_961167_idx')],
                'constraints': [models.UniqueConstraint(fields=('coupon', 'order'), name='unique_coupon_per_order')],
            },
        ),
    ]
