# Generated by Django 6.0.1 on 2026-02-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_mode',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20),
        ),
    ]
