# Generated by Django 6.0.1 on 2026-03-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.CharField(default='global', max_length=100),
        ),
    ]
