# Generated by Django 6.0.1 on 2026-03-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_is_featured_product_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('digital', 'Digital'), ('topup', 'Top-up')], max_length=20),
        ),
    ]
