# Generated by Django 6.0.1 on 2026-02-18 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=500, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='codes_fulfi_content_c2870f_idx'), models.Index(fields=['is_used'], name='codes_fulfi_is_used_33b479_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_used', True), ('used_at__isnull', False)), ('is_used', False), _connector='OR'), name='valid_used_state')],
            },
        ),
    ]
