# Generated by Django 6.0.1 on 2026-03-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillmentcode',
            name='code',
            field=models.CharField(max_length=500),
        ),
    ]
