# Generated by Django 6.0.1 on 2026-02-18 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('topup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='topup_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='topup.topuppackage'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'topup_package'), name='unique_cart_product_package'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('topup_package__isnull', True)), fields=('cart', 'product'), name='unique_cart_product_no_package'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_topup', True), ('topup_package__isnull', False)), models.Q(('is_topup', False), ('topup_package__isnull', True)), _connector='OR'), name='valid_topup_logic'),
        ),
    ]
