# Generated by Django 6.0.1 on 2026-02-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='topup_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
