# Generated by Django 6.0.1 on 2026-02-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_topup_data'),
        ('catalog', '0003_alter_product_options_alter_product_stock_mode'),
        ('topup', '0004_rename_input_length_topupfield_min_input_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_product_package',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='topup_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'topup_package', 'topup_hash'), name='unique_cart_product_package_hash'),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='topup_data',
        ),
    ]
