# Generated by Django 6.0.1 on 2026-03-04 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cartitem_unique_cart_product_package_and_more'),
        ('coupons', '0002_alter_coupon_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='coupons.coupon'),
        ),
    ]
