# Generated by Django 6.0.1 on 2026-03-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='topup_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
