# Generated by Django 6.0.1 on 2026-02-18 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('topup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='topup_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='topup.topuppackage'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='orders_orde_user_id_a87c6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product', 'topup_package'), name='unique_order_product_package'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_topup', True), ('topup_package__isnull', False)), models.Q(('is_topup', False), ('topup_package__isnull', True)), _connector='OR'), name='valid_order_topup_logic'),
        ),
    ]
