# Generated by Django 6.0.1 on 2026-03-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_discount_total_alter_order_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('completed', 'Completed'), ('processing', 'Processing'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
