# Generated by Django 6.0.1 on 2026-03-03 21:12

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('email_type', models.CharField(choices=[('none', 'None'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('order_success', 'Order Success'), ('order_failed', 'Order Failed'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_returned', 'Order Returned'), ('order_refunded', 'Order Refunded'), ('order_cancelled', 'Order Cancelled'), ('code_sent', 'Code Sent'), ('redeem_link', 'Redeem Link'), ('default', 'Default')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_emailed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('readed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='notificatio_user_id_c291d5_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_9edb86_idx'), models.Index(fields=['is_deleted'], name='notificatio_is_dele_13dd60_idx'), models.Index(fields=['is_emailed'], name='notificatio_is_emai_30835a_idx'), models.Index(fields=['is_active'], name='notificatio_is_acti_7de9ed_idx')],
            },
            managers=[
                ('public_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
