# Generated by Django 6.0.1 on 2026-03-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='notification',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='email_type',
            field=models.CharField(choices=[('none', 'None'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('order_success', 'Order Success'), ('order_failed', 'Order Failed'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_returned', 'Order Returned'), ('order_refunded', 'Order Refunded'), ('order_cancelled', 'Order Cancelled'), ('code_sent', 'Code Sent'), ('redeem_link', 'Redeem Link'), ('credits_delivered', 'Credits Delivered'), ('default', 'Default')], max_length=20),
        ),
    ]
